### ISSUE TITLE
new compile error 

### ISSUE THREAD

**Issue by balamsoto** [sparkfun/SparkFun_LSM9DS1_Arduino_Library#3]
just download new version and getting buch of

/LSM9DS1_Basic_I2C.ino: In function 'void printMag()':
LSM9DS1_Basic_I2C:197: error: 'Serial' was not declared in this scope
   Serial.print("M: ");
   ^

LSM9DS1_Basic_I2C:244: error: 'Serial' was not declared in this scope
   Serial.print("Pitch, Roll: ");
   ^
exit status 1
'Serial' was not declared in this scope

**Comment by bboyho** [comment]
Hi,

I am not sure what version of your Arduino IDE and this library that you are using. I did not have any issues compiling the **LSM9DS1_Basic_I2C.ino** example with Arduino IDE v1.8.3 and v1.8.3. Considering the other issue [ https://github.com/sparkfun/LSM9DS1_Breakout/issues/6  ] that you had reported in the product repo was due to the Arduino IDE version, you may be experiencing a similar issue. Since the Serial library is part of the core libraries in the Arduino IDE, I have a feeling it may be due to the version that you are using on your computer.

Try reinstalling the Arduino IDE and this library to see if that is able to fix the issue with it compiling. Otherwise, try using a different Arduino IDE version.

**Comment by balamsoto** [comment]
thanks for the reply, I had that problem back in 2016 few weeks after and update fixed the bug
